# Generated by Django 3.2.8 on 2021-11-26 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo?')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='excluido?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='parceiro')),
                ('erp_contract_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='codigo do contrato no erp')),
            ],
            options={
                'verbose_name': 'parceiro (empresa)',
                'verbose_name_plural': 'parceiros (empresa)',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo?')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='excluido?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.partner', verbose_name='parceiro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'usuario (parceiro)',
                'verbose_name_plural': 'usuarios (parceiro)',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MonitorNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo?')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='excluido?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='descrição')),
                ('link', models.CharField(max_length=255, verbose_name='link do mapa')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.partner', verbose_name='parceiro')),
            ],
            options={
                'verbose_name': 'Mapa de monitoramento',
                'verbose_name_plural': 'Mapas de monitoramento',
            },
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo?')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='excluido?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('username', models.CharField(error_messages={'unique': 'Este usuário já está em uso.'}, help_text='Informação usuada para o cliente fazer login no serviço', max_length=255, unique=True, verbose_name='usuário')),
                ('password', models.CharField(help_text='Senha que o cliente usará no login do serviço', max_length=255, verbose_name='senha')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='nome completo')),
                ('phone', models.CharField(max_length=17, null=True, verbose_name='telefone')),
                ('status', models.CharField(choices=[('1', 'normal'), ('2', 'bloqueado')], default=1, max_length=1, verbose_name='status')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='endereço')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='cidade')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('provided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.partner', verbose_name='fornecido por')),
            ],
            options={
                'verbose_name': 'usuário (oxentetv)',
                'verbose_name_plural': 'usuários (oxentetv)',
                'ordering': ('-created_at',),
            },
        ),
    ]
