# Generated by Django 3.2.8 on 2021-11-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(help_text='senha que o cliente usará no login do serviço', max_length=255, verbose_name='senha'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(help_text='informação usuada para o cliente fazer login no serviço', max_length=255, unique=True, verbose_name='usuário'),
        ),
    ]
