# Generated by Django 3.2.8 on 2021-11-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211120_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='cidade'),
        ),
    ]
