# Generated by Django 3.2.8 on 2021-11-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customeruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Este usuário já está em uso.'}, help_text='Informação usuada para o cliente fazer login no serviço', max_length=255, unique=True, verbose_name='usuário'),
        ),
    ]
