# Generated by Django 3.2.8 on 2021-11-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customeruser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='erp_people_code',
        ),
        migrations.CreateModel(
            name='MonitorNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo?')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='excluido?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='descrição')),
                ('link', models.CharField(max_length=255, verbose_name='link do mapa')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.partner', verbose_name='parceiro')),
            ],
            options={
                'verbose_name': 'Mapa de monitoramento',
                'verbose_name_plural': 'Mapas de monitoramento',
            },
        ),
    ]
